sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t drishdocker93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true drishdocker93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-572431736115"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"